name: PHPUNIT

on: [push]

env:
  XDEBUG_MODE: coverage

jobs:
  Run-Tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: xdebug, ssh2
      - run: composer install -noa
      - run: vendor/bin/phpunit --coverage-text
